- name: Create the systemd service file
  template:
    src: service.j2
    dest: /etc/systemd/system/{{ systemd_service_name }}.service
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload systemd
    - Restart service
- name: Enable & start the service
  systemd:
    name: "{{ systemd_service_name }}"
    state: started
    enabled: true
